### PR TITLE
Weather refactor

### PR DESCRIPTION
**Pull request by ericthelin**
This improves the code in lots of small ways. But it also brings in high and low temperature displays on both the today orb and the forecast orb.

### CODE REVIEW

**Comment by ericthelin** [comment]
There will be one more refactor at some point to introduce a data model class. But that can wait and be a separate PR.

**Review by tecnovel — CHANGES_REQUESTED** [review]
Do I need to change something in the config.h? no right? because i have some weir behavior here.
Mittel (IMG_1492)
Mittel (IMG_1493)
Mittel (IMG_1494)

- The Stock Widget showed only one stock, and now after a while waiting the others where loaded too. 
- in the weather widget i have an error printed out: CertificatePoliciesJ... (should be the date there)
- On the big temperature orb, can you add a space between the number and the ° ?

**Comment by tecnovel** [comment]
I haven't looked into the code and did not debug anything. I don't have time at the moment, sorry, but i will later this weekend. but maybe you can solve it already until then...

**Comment by ericthelin** [comment]
for the certificate issue that is well outside of these changes. still an issue but unrelated.
for the stocks there isn't any retry logic on failures it just skips the update for that stock. Which is unfortunate when it is the initial load.
I will add a little more space before the degree symbol. Finding the right distance is a little tricky now because it is autocalculated.

**Review by tecnovel — APPROVED** [review]
okey, let's do the other stuff in another PR

**Pull request merged**
