### PR TITLE
WiFiManager fixes

### PR DESCRIPTION
**Pull request by KanyonKris**
Original PR #76 got closed when I synced so opening a new PR for the requested fixes.

### CODE REVIEW

**Comment by KanyonKris** [comment]
I give up. I keep getting conflicts and weird errors and I'm sick of fixing minor formatting. If you can use these PRs, great. If not you can make the code changes yourself. Pretty bummed about trying to contribute.

**Comment by KanyonKris** [comment]
I give up. I keep getting conflicts and weird errors and I'm sick of fixing minor formatting. If you can use these PRs, great. If not you can make the code changes yourself. Pretty bummed about trying to contribute.

**Comment by brett-dot-tech** [comment]
Hey @KanyonKris, I'm so sorry about this. 
This has been on my list to button up and ship for some time now but my time was taken up by correcting the stock widget. Your frustration is very warranted and I take 100% of the blame for that, sorry.

Would you be able to open this PR so I can work off of it and get things buttoned up? I'm just not able to work off of it if its closed.

I want to make sure its tied to your PR and not just stuff copied over so you get the credit for all of the changes.

Again; on me, thank you for taking this on and everything you've done so far.

**Comment by KanyonKris** [comment]
@brett-dot-tech thanks for reaching out. My main frustration is github learning curve.
I can't open this PR because <some cryptic github error>. I'll do a new PR when I get home.
Eventually I'd like to have all config settings in the portal so the user doesn't have to edit config.h (and users could install binaries instead of compiling). But setting up WiFi is the first step.

**Pull request closed without merging**
