### PR TITLE
fix clock flicker for am/pm

### PR DESCRIPTION
**Pull request by ericthelin**
The clock does a full redraw each time so wiping the display is not needed.

### CODE REVIEW

**Review by Jkitche — APPROVED** [review]

**Review by tecnovel — CHANGES_REQUESTED** [review]
IMG_1456

If you take out the display.fillScreen(TFT_BLACK); the screen has to be cleared somewhere else. (On the picture you see the first and last letter of my wifi name)

**Review by tecnovel — COMMENTED** [review]
looks good(at least with refreshing the screens). but i found something weird, i just tested with these settings:
#define TIME_ZONE_OFFSET 2
#define FORMAT_24_HOUR false

An its 2:49(in the night) in my country but it shows 2:49 pm. did someone else a 24h test?

**Comment by ericthelin** [comment]
yeah, the am/pm is broken at this point. in theory fixed in https://github.com/brettdottech/info-orbs/pull/25

**Comment by ericthelin** [comment]
> looks good(at least with refreshing the screens). but i found something weird, i just tested with these settings: #define TIME_ZONE_OFFSET 2 #define FORMAT_24_HOUR false
> 
> An its 2:49(in the night) in my country but it shows 2:49 pm. did someone else a 24h test?

Jae's fixes are merged now. So it should be fixed now.

**Review by tecnovel — APPROVED** [review]
looks good

**Pull request merged**
