### PR TITLE
MQTTwidget - support for the delivery of MQTT topic data realtime to your info-orbs!

### PR DESCRIPTION
**Pull request by nutkracker**
Has been working well for me so probalary time now to look at merging this into DEV.

### CODE REVIEW

**Comment by AlbertDijksma** [comment]
Hello Nuttracker,
I have been testing with your version for a while but I can't get it to work properly with the "jsonfield".
I can't get the values ​​"installed_version" and "value" out of the two examples below.

======
{
  "brightness": 132,
  "linkquality": 140,
  "power_on_behavior": null,
  "state": "OFF",
  "update": {
    "installed_version": 587810353,
    "latest_version": 587810353,
    "state": "idle"
  },
  "update_available": false
}
======

======
{
  "power_delivered_l1": [
    {
      "value": 0.438,
      "unit": "kW"
    }
  ]
}
======

**Comment by nutkracker** [comment]
@AlbertDijksma can you share the details of your setup topic contents?  Its this configuration that needs to be setup so that its aware of the MQTT topics that you have above.

**Comment by AlbertDijksma** [comment]
**json multiple arrays problem**

**-Topic: zigbee2mqtt/Woonkamer eettafel**
{
  "brightness": 132,
  "linkquality": 140,
  "power_on_behavior": null,
  "state": "OFF",
  "update": {
    "installed_version": 587810353,
    "latest_version": 587810353,
    "state": "idle"
  },
  "update_available": false
}


**-Topic: DSMR-API/power_delivered_l1**
{
  "power_delivered_l1": [
    {
      "value": 0.438,
      "unit": "kW"
    }
  ]
}


**-Setup**
{
  "orbs": [
    {
      "orbid": 0,
      "orbdesc": "Power",
      "orb-bg": "TFT_SILVER",
      "orb-textcol": "TFT_BLACK",
      "topicsrc": "DSMR-API/power_delivered_l1",
      "xpostxt": 110,
      "ypostxt": 1,
      "xposval": 140,
      "yposval": 1,
      "orbsize": 3,
      "orbvalunit": "kW",
      "jsonfield": "value"
    },
    {
      "orbid": 1,
      "orbdesc": "brightness test",
      "orb-bg": "TFT_BLUE",
      "orb-textcol": "TFT_WHITE",
      "topicsrc": "zigbee2mqtt/Woonkamer eettafel",
      "xpostxt": 110,
      "ypostxt": 1,
      "xposval": 140,
      "yposval": 1,
      "orbsize": 3,
      "orbvalunit": "%",
      "jsonfield": "brightness"
    },
    {
      "orbid": 2,
      "orbdesc": "jsontest",
      "orb-bg": "TFT_BLUE",
      "orb-textcol": "TFT_WHITE",
      "topicsrc": "zigbee2mqtt/Woonkamer eettafel",
      "xpostxt": 110,
      "ypostxt": 1,
      "xposval": 140,
      "yposval": 1,
      "orbsize": 3,
      "orbvalunit": "tst",
      "jsonfield": "installed_version"
    },
    {
      "orbid": 3,
      "orbdesc": "PV Solar Tdy+",
      "orb-bg": "TFT_BLUE",
      "orb-textcol": "TFT_WHITE",
      "topicsrc": "hamqtt/sensor/solcast_pv_forecast_forecast_tomorrow/state",
      "xpostxt": 110,
      "ypostxt": 1,
      "xposval": 140,
      "yposval": 1,
      "orbsize": 3,
      "orbvalunit": "kWh"
    },
    {
      "orbid": 4,
      "orbdesc": "Garage temp",
      "orb-bg": "TFT_BLUE",
      "orb-textcol": "TFT_WHITE",
      "topicsrc": "DShgghgMR-API/mbus1_delivered",
      "xpostxt": 110,
      "ypostxt": 1,
      "xposval": 140,
      "yposval": 1,
      "orbsize": 3,
      "orbvalunit": "'c",
      "jsonfield": "value"
    }
  ]
}

**Comment by nutkracker** [comment]
Thanks.  I’ll take a look.

**Comment by nutkracker** [comment]
@AlbertDijksma Had a bit of a mare with Git and getting this update made to my earlier PR - so hopefully this has worked! :-)

So the latest code should now include support for nested JSON.  In your earlier example, you will need to set the jsonfield to **update.installed_version** to extract that value out.  I've copied your exact payload on myside and can confirm this works.  Replacing update.installed_version with brightness will also work too!

I've also fixed the hardcoded setting of orb-textcol to WHITE - something I had left in from an earlier exercise (thanks to @breiti on Discord for spotting that)

**Comment by AlbertDijksma** [comment]
@nutkracker
Thanks for your quick solution.
I'm testing but can't get it to work yet.
Here's my setup:

Topic: info-orbs/setup/orbs
{
  "orbs": [
    {
      "orbid": 0,
      "orbdesc": "Power",
      "orb-bg": "TFT_SILVER",
      "orb-textcol": "TFT_BLACK",
      "topicsrc": "DSMR-API/power_delivered",
      "xpostxt": 110,
      "ypostxt": 1,
      "xposval": 140,
      "yposval": 1,
      "orbsize": 3,
      "orbvalunit": "kW",
      "jsonfield": "power_delivered.value"
    }, …………..


Topic: DSMR-API/power_delivered
{
  "power_delivered": [
    {
      "value": 0.255,
      "unit": "kW"
    }
  ]
}

Serial monitor:
Message arrived [DSMR-API/power_delivered]: {"power_delivered": [{"value": 0.255, "unit": "kW"}]}
JSON field 'power_delivered.value' not found in payload.

**Comment by nutkracker** [comment]
@AlbertDijksma ok, this latest version supports JSON arrays.
So your jsonfield value should be something like: power_delivered[0].value
Give that a try.  I've tested this and the previous two supported options and they also work - so hopefully that should give you everything you need.  Thank you for your examples, really helpful!  Let me know how you get on!

**Comment by AlbertDijksma** [comment]
@nutkracker 
Parssing the json value works perfectly now.
Maybe another point for improvement, when receiving a new value the relevant orb flashes.
In my case every 15 seconds.
Maybe also a future request, it would be great if there was support for gauges.
Thanks a lot for the quick support.

**Comment by nutkracker** [comment]
Good to hear this is working!  The flashing is likely the redrawing of the orb on value updates.  That said, I suspect a redraw is happening even if the attribute you’re displaying hasn’t changed but another attribute on the topic has.  I have noticed this myself and will add to the “todo”.  I think for now it’s good enough.

**Comment by nutkracker** [comment]
@AlbertDijksma I've just added support to only redraw the orb for JSON attributes that are being shown - so if a MQTT topic has multiple attributes and they are changing, the orb won't redraw unless that attribute itself has changed.  I've only tested this briefly but so far so good.

**Comment by lyricnz** [comment]
FYI I tested this yesterday, and it worked fine.  It would be nice to have some more non-hardcoded visualisation options, but that can totally be future-PR.

**Comment by nutkracker** [comment]
This PR replaced with https://github.com/brettdottech/info-orbs/pull/132

**Pull request closed without merging**
