### PR TITLE
refactor weather widget to use a data model

### PR DESCRIPTION
**Pull request by ericthelin**

### CODE REVIEW

**Comment by brammie15** [comment]
Code looking good!

Gonna wait for some1 else to approve but looks good (Will give it a quick test :p)

**Review by tecnovel — CHANGES_REQUESTED** [review]
add MAX_RETRIES define to the config

when you push the button, it should change at the 3days forecast high and low temp, but it does not. it looks right in the weatherwidget.cpp so the bug has to be when loading the data

**Review by tecnovel — APPROVED** [review]

**Comment by tecnovel** [comment]
@ericthelin do you accept my bugfix? (i can not request a review from you here)

**Comment by ericthelin** [comment]
> @ericthelin do you accept my bugfix? (i can not request a review from you here)

Good catch

**Pull request merged**
