### PR TITLE
Display hh:mm when visual crossing weather data was last updated

### PR DESCRIPTION
**Pull request by HugoBalder**
The data downloaded from visual crossing has a timestamp, when the data was last updated. This will be shown below the weather conditions on the second screen of the weather widget.

### CODE REVIEW

**Comment by flattermann** [comment]
You did a lot of code format changes in this PR, was this intended?

See
https://github.com/brettdottech/info-orbs/pull/101/files

I would rather split the code changes and the format changes into different PRs.
Maybe use this PR only for code changes.

Regarding the format changes, I also tried to start a discussion in Discord.
My dream would be if all files use the same code format. :-)

**Comment by HugoBalder** [comment]
I don't know why this format changes happened. I downloaded the current dev branch and opened it then in my Visual Code. Seems that some setting in VS Code made these changes. I saw the discussion on Discord and it would be good to have the same formatting and settings.

I don't know now how to split the format changes and code changes.

**Comment by HugoBalder** [comment]
I just imported e.g. the (original) weatherdatamodel.h, applied my changes and saved it in VS Code. After that, the format changes were applied :(((( Now it's the question, how can this be prohibited, so that e.g. no new lines are inserted at the places with { ???

**Comment by flattermann** [comment]
You probably opened the workspace "info-orbs.code-workspace" in VS Code.
Normally, that's a good thing, because it can contain settings liks "formatOnSave=true".
At the moment, it's a problem, because most of the code is not formatted.

For now, I would recommend you close the workspace (File / Close Workspace).
Afterwards, re-open the project by File / Open Folder and select the info-orbs root folder.

If you want to reopen the workspace later, just click on the info-orbs.code-workspace file and select "Open Workspace".

**Comment by HugoBalder** [comment]
Got it, thanks for the tips :) Will try and upload the files again, hopefully without this formatting issues.

**Pull request closed without merging**
